import fs from 'node:fs';
import path from 'node:path';

// Test-harness pieces the runner owns, injected into the work tree and never
// visible in the tutorial's own files. Re-applied before every assertion phase
// because an overlay may have replaced Cargo.toml or build.rs in between.
// Two landmines:
//  - tauri::test is behind the `test` feature (dev-dependency)
//  - on Windows the test exe needs the comctl32 v6 manifest, which only
//    rustc-link-arg-tests can attach, and only to integration-test targets

const DEV_DEP_BLOCK = `
# tatu:harness — tauri::test is feature-gated
[dev-dependencies]
tauri = { version = "2", features = ["test"] }
`;

const BUILD_RS_BLOCK = `// tatu:harness — cargo test exes need the comctl32 v6 manifest on Windows
// (tauri-build embeds it for bins only; without this the test exe dies at load
// with STATUS_ENTRYPOINT_NOT_FOUND on TaskDialogIndirect)
#[cfg(windows)]
fn tatu_test_manifest() {
    let manifest = std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tatu-test-manifest.xml");
    println!("cargo::rustc-link-arg-tests=/MANIFEST:EMBED");
    println!("cargo::rustc-link-arg-tests=/MANIFESTINPUT:{}", manifest.display());
}
#[cfg(not(windows))]
fn tatu_test_manifest() {}
`;

const MANIFEST_XML = `<assembly xmlns="urn:schemas-microsoft-com:asm.v1" manifestVersion="1.0">
  <dependency>
    <dependentAssembly>
      <assemblyIdentity
        type="win32"
        name="Microsoft.Windows.Common-Controls"
        version="6.0.0.0"
        processorArchitecture="*"
        publicKeyToken="6595b64144ccf1df"
        language="*"
      />
    </dependentAssembly>
  </dependency>
</assembly>
`;

export function ensureHarness(workDir) {
  const srcTauri = path.join(workDir, 'src-tauri');

  const cargoToml = path.join(srcTauri, 'Cargo.toml');
  let toml = fs.readFileSync(cargoToml, 'utf8');
  if (!toml.includes('tatu:harness')) {
    fs.writeFileSync(cargoToml, toml.trimEnd() + '\n' + DEV_DEP_BLOCK);
  }

  const buildRs = path.join(srcTauri, 'build.rs');
  let build = fs.readFileSync(buildRs, 'utf8');
  if (!build.includes('tatu:harness')) {
    build = BUILD_RS_BLOCK + '\n' + build.replace(/fn main\(\)\s*\{/, 'fn main() {\n    tatu_test_manifest();');
    fs.writeFileSync(buildRs, build);
  }

  const manifestXml = path.join(srcTauri, 'tatu-test-manifest.xml');
  if (!fs.existsSync(manifestXml)) fs.writeFileSync(manifestXml, MANIFEST_XML);

  fs.mkdirSync(path.join(srcTauri, 'tests'), { recursive: true });
}

// One generated integration-test file per assertion phase: a process can only
// host one Tauri app, so each phase gets its own test binary.
// `harness.prelude` in tutorial.yaml carries verbatim
// Rust (e.g. a copy of the app command under test: #[tauri::command] handlers
// aren't importable across crates).
export function generateIpcTestFile({ name, prelude, plugins, handlers, cases }) {
  const pluginLines = (plugins ?? []).map((p) => `        .plugin(${p}::init())`).join('\n');
  const handlerList = (handlers ?? []).join(', ');

  const tests = cases
    .map((c, i) => {
      const fnName = `${sanitize(c.label ?? `case_${i}`)}`;
      return `#[test]
fn ${fnName}() {
    let app = build_app();
${c.setup ? indent(c.setup, 4) : ''}    let webview = tauri::WebviewWindowBuilder::new(&app, "main", Default::default())
        .build()
        .unwrap();
    let res = get_ipc_response(
        &webview,
        InvokeRequest {
            cmd: ${JSON.stringify(c.command)}.into(),
            callback: CallbackFn(0),
            error: CallbackFn(1),
            url: "http://tauri.localhost".parse().unwrap(),
            body: InvokeBody::Json(serde_json::from_str(r#"${JSON.stringify(c.args ?? {})}"#).unwrap()),
            headers: Default::default(),
            invoke_key: INVOKE_KEY.to_string(),
        },
    );
${expectBlock(c.expect)}
}`;
    })
    .join('\n\n');

  return `// generated by tatu — do not edit; regenerated on every run
#![allow(unused_imports, dead_code)]
use tauri::ipc::{CallbackFn, InvokeBody};
use tauri::test::{get_ipc_response, mock_builder, INVOKE_KEY};
use tauri::webview::InvokeRequest;
use tauri::Manager;

${prelude ?? ''}

fn build_app() -> tauri::App<tauri::test::MockRuntime> {
    mock_builder()
${pluginLines}
        .invoke_handler(tauri::generate_handler![${handlerList}])
        .build(tauri::generate_context!())
        .expect("failed to build app from real context")
}

${tests}
`;
}

function expectBlock(expect) {
  if (expect === 'denied') {
    return `    let err = res.expect_err("expected an ACL denial");
    let msg = err.to_string();
    assert!(msg.contains("not allowed"), "expected ACL denial, got: {msg}");`;
  }
  // Raw is the plugin-byte-response case (e.g. fs read_text_file); Json is the
  // common command-return case — both normalize to text before comparing
  const NORMALIZE = `    let body = res.expect("expected the command to succeed");
    let text = match body {
        tauri::ipc::InvokeResponseBody::Raw(bytes) => String::from_utf8_lossy(&bytes).to_string(),
        tauri::ipc::InvokeResponseBody::Json(s) => s,
    };`;
  if (expect && typeof expect === 'object' && 'ok' in expect) {
    return `${NORMALIZE}
    let value: serde_json::Value = serde_json::from_str(&text).unwrap_or(serde_json::Value::String(text.clone()));
    let expected: serde_json::Value = serde_json::from_str(r#"${JSON.stringify(expect.ok)}"#).unwrap();
    assert_eq!(value, expected, "unexpected response: {text}");`;
  }
  if (expect && typeof expect === 'object' && 'ok_contains' in expect) {
    return `${NORMALIZE}
    assert!(text.contains(${JSON.stringify(expect.ok_contains)}), "unexpected response: {text}");`;
  }
  throw new Error(`unsupported expect: ${JSON.stringify(expect)}`);
}

export function sanitize(s) {
  return s.replace(/[^a-zA-Z0-9_]/g, '_');
}

function indent(text, n) {
  const pad = ' '.repeat(n);
  return (
    text
      .split('\n')
      .map((l) => (l.trim() ? pad + l : l))
      .join('\n') + '\n'
  );
}
