use std::fmt::Write as _;

use crate::error::{Error, Result};

/// TypeScript interfaces for the manifest contract, generated from the same
/// schemars schema that produces manifest.schema.json. tauri-docs commits the
/// output next to its components so the docs repo needs zero extra
/// dependencies to stay drift-free.
pub fn manifest_types_ts() -> Result<String> {
  let schema = schemars::schema_for!(crate::manifest::Manifest);
  let root = serde_json::to_value(&schema)?;

  let mut out = String::from(
    "// generated by `tatu schema --emit-ts` — do not edit; regenerate from the runner\n\n",
  );

  emit_type(&mut out, "TutorialManifest", &root)?;
  if let Some(defs) = root.get("$defs").and_then(|d| d.as_object()) {
    for (name, def) in defs {
      emit_type(&mut out, &ts_name(name), def)?;
    }
  }
  Ok(out)
}

fn ts_name(schema_name: &str) -> String {
  match schema_name {
    "StepRecord" => "TutorialStepRecord".to_string(),
    "AssertionKind" => "TutorialAssertionKind".to_string(),
    other => other.to_string(),
  }
}

fn emit_type(out: &mut String, name: &str, def: &serde_json::Value) -> Result<()> {
  // enums (e.g. Status) come out as {"type":"string","enum":[...]}
  if let Some(variants) = def.get("enum").and_then(|e| e.as_array()) {
    let union = variants
      .iter()
      .map(|v| format!("'{}'", v.as_str().unwrap_or_default()))
      .collect::<Vec<_>>()
      .join(" | ");
    writeln!(out, "export type {name} = {union};\n").expect("write to string");
    return Ok(());
  }

  let Some(properties) = def.get("properties").and_then(|p| p.as_object()) else {
    return Err(Error::Runner(format!(
      "schema type {name} has no properties or enum"
    )));
  };
  let required: Vec<&str> = def
    .get("required")
    .and_then(|r| r.as_array())
    .map(|a| a.iter().filter_map(|v| v.as_str()).collect())
    .unwrap_or_default();

  writeln!(out, "export interface {name} {{").expect("write to string");
  for (prop, prop_schema) in properties {
    if let Some(description) = prop_schema.get("description").and_then(|d| d.as_str()) {
      writeln!(out, "  /** {description} */").expect("write to string");
    }
    let optional = if required.contains(&prop.as_str()) {
      ""
    } else {
      "?"
    };
    writeln!(out, "  {prop}{optional}: {};", ts_type(prop_schema)).expect("write to string");
  }
  writeln!(out, "}}\n").expect("write to string");
  Ok(())
}

fn ts_type(prop: &serde_json::Value) -> String {
  if let Some(reference) = prop.get("$ref").and_then(|r| r.as_str()) {
    return ts_name(reference.rsplit('/').next().unwrap_or(reference));
  }
  // Option<T> comes out as {"type": ["T", "null"]} — take the non-null member
  let type_name = match prop.get("type") {
    Some(serde_json::Value::String(t)) => Some(t.as_str()),
    Some(serde_json::Value::Array(types)) => types
      .iter()
      .filter_map(|t| t.as_str())
      .find(|t| *t != "null"),
    _ => None,
  };
  match type_name {
    Some("string") => "string".to_string(),
    Some("boolean") => "boolean".to_string(),
    Some("integer") | Some("number") => "number".to_string(),
    Some("array") => {
      let items = prop
        .get("items")
        .map(ts_type)
        .unwrap_or_else(|| "unknown".to_string());
      format!("{items}[]")
    }
    _ => "unknown".to_string(),
  }
}

#[cfg(test)]
mod tests {
  // every property in the manifest schema must appear in the emitted TypeScript —
  // adding a Rust field without teaching the emitter fails cargo test
  #[test]
  fn emitted_ts_covers_every_schema_property() {
    let ts = super::manifest_types_ts().unwrap();
    let schema = serde_json::to_value(schemars::schema_for!(crate::manifest::Manifest)).unwrap();

    let mut props: Vec<String> = Vec::new();
    collect_props(&schema, &mut props);
    if let Some(defs) = schema.get("$defs").and_then(|d| d.as_object()) {
      for def in defs.values() {
        collect_props(def, &mut props);
      }
    }
    assert!(!props.is_empty());
    for prop in props {
      assert!(
        ts.contains(&format!("{prop}: ")) || ts.contains(&format!("{prop}?: ")),
        "schema property {prop} missing from emitted TypeScript:\n{ts}"
      );
    }
  }

  fn collect_props(def: &serde_json::Value, out: &mut Vec<String>) {
    if let Some(properties) = def.get("properties").and_then(|p| p.as_object()) {
      out.extend(properties.keys().cloned());
    }
  }
}
